from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView
from myaccount.models import UserProfile

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=UserProfile.objects.order_by('-subscription_date')[:5],
            context_object_name='latest_userprofile_list',
            # autogenerated name would be "userprofile_list"
            #template_name='myaccounts/userprofile_list.html'
            )
            # default is myaccount/userprofile_list.html
        ),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=UserProfile,
            template_name='myaccount/userprofile_detail.html')
            # default is myaccount/userprofile_detail.html
        ),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=UserProfile,
            template_name='myaccount/userprofile_results.html'),
            # Goes to myaccount/userprofile_detail.html by default, as a DetailView
        name='userprofile_results'),
#    url(r'^(?P<poll_id>\d+)/vote/$', 'myaccount.views.vote'),
)



