from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView, TemplateView
from polls.models import Poll
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$',
        login_required(ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            # autogenerated name would be "poll_list"
            #template_name='polls/index.html'
            )
            # default is polls/poll_list.html
        )),
    url(r'^(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=Poll,
            template_name='polls/poll_detail.html')
            # default is polls/poll_detail.html
        )),
    url(r'^(?P<pk>\d+)/results/$',
        login_required(DetailView.as_view(
            model=Poll,
            template_name='polls/poll_results.html')),
            # Goes to polls/poll_detail.html by default, as a DetailView
        name='poll_results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),
)



